function p = setrigpath2
%------------------------------------------------------------------------
% p = setrigpath2
%------------------------------------------------------------------------
% 
% sets up path
% 
%------------------------------------------------------------------------
% Input Arguments:
%     none 
% Output Arguments:
%    p    path string
%------------------------------------------------------------------------
% See also: 
%------------------------------------------------------------------------

%------------------------------------------------------------------------
%  Sharad J. Shanbhag
%    sharad.shanbhag@einstein.yu.edu
%------------------------------------------------------------------------
% Created: ??? (SJS)
%
% Revisions:
%   2 December, 2009 (SJS): added documentation
%   06 May, 2010 (GA): modified to fit UMD PC matlab settings
%   12 Dec, 2011 (GA): modified to fit Oldenburg matlab settings
%   20 May, 2012 (GA): added FOCHS and subdirectories of toolbox2
%------------------------------------------------------------------------
% TO DO:
%------------------------------------------------------------------------
    c = computer;
    switch c
        case {'PCWIN', 'PCWIN64'}    
            p = path(labpathdef,path);
        otherwise
            error([c ' is unknown computer'])
        end
%-------------------------------------------------------------------------

%-------------------------------------------------------------------------
function p = labpathdef(varargin)
if ~nargin
    tytopath = 'C:\TytoLogy\'
    toolpath = [tytopath 'toolbox\']
    tytopath2 = 'C:\TytoLogy2\'
else
    tytopath = [varargin{1} '\']
    toolpath = [tytopath 'toolbox\']
    tytopath2 = [varargin{2} '\']
end

p = [...
%%% BEGIN ENTRIES %%%
    'C:\TDT\ActiveX;', ...
    [tytopath2 ';'], ...
    [tytopath2 'toolbox2;'], ... 
    [tytopath2 'toolbox2\CALtools;'], ... 
    [tytopath2 'toolbox2\TDTcircuits;'], ... 
    [tytopath2 'toolbox2;'], ... 
    [tytopath2 'HPSearch2;'], ...
    [tytopath2 'HeadPhoneCal2;'], ...
    [tytopath2 'MicroPhoneCal2;'], ...
    [tytopath2 'FOCHS;'], ...
    [tytopath2 'TytoView;'], ...
    [tytopath ';'], ...
    [toolpath ';'], ...
    [toolpath 'BinaryFileToolbox;'], ...
    [toolpath 'Audio;'], ...
    [toolpath 'Audio\Calibration;'], ...
    [toolpath 'Audio\FFT;'], ...
    [toolpath 'Audio\Filter;'], ...
    [toolpath 'Audio\Synthesis;'], ...
    [toolpath 'Audio\Utils;'], ...
    [toolpath 'Multiplexer;'], ...
    [toolpath 'SpeakerLocations;'], ...
    [toolpath 'TDT\Functions;'], ...
    [toolpath 'TDT\Functions\InputOutput;'], ...
    [toolpath 'TDT\Functions\PA5;'], ...
    [toolpath 'TDT\Functions\RP;'], ...
    [toolpath 'TDT\Functions\RX5;'], ...
    [toolpath 'TDT\Functions\RX8;'], ...
    [toolpath 'TDT\Functions\Robot;'], ...
    [toolpath 'TDT\Functions\zBUS;'], ...
    [toolpath 'Utilities;'], ...
    [toolpath 'RFAnalyze;'], ...
    [toolpath 'Robot\TDTRobot;'], ...
    [toolpath 'UIutilities;'], ...
    [toolpath 'structdlg;'], ...
    [toolpath 'TytoLogyTools;'], ...
    [tytopath 'Calibration\MicrophoneCal;'], ...
    [tytopath 'Calibration\HeadphoneCal;'], ...
    [tytopath 'Calibration\CalibrationData;'], ...
    [tytopath 'Calibration\FreeField\FFCal;'], ...
    [tytopath 'Calibration\FreeField\ProcessFFCal;'], ...
    [tytopath 'Calibration\FreeField\SpeakerData;'], ...
    [tytopath 'Experiments\HPSearch;'], ...
    [tytopath 'Experiments\HPSearch\Functions;'], ...
    [tytopath 'Experiments\HPSearch\Protocols;'], ...
    [tytopath 'Experiments\HPSearch\Documents;'], ...
    [tytopath 'Experiments\FreeField\SpeakerMatrix;'], ...
    [tytopath 'Experiments\FreeField\FreeFieldRF;'], ...
    [tytopath 'Experiments\FreeField\MPxMon;'], ...
    [tytopath 'Experiments\FreeField\ProCell;'], ...
    [tytopath 'Experiments\FreeField\RevRF;'], ...
%%% END ENTRIES %%%
      ...
];

p = [userpath,p];
%-------------------------------------------------------------------------
